### ISSUE TITLE
Static assets are not delivered

### ISSUE THREAD

**Issue by kristianschneider** [alexsee/umbraco-container#1]
Hi.
Thanks for making this.
I am trying it out but seem to run into an issue where/umbraco/assets and /umbraco/lib/ are not delivered.
Any suggestions? I assume its related to  webBuilder.UseStaticWebAssets();
![image](https://user-images.githubusercontent.com/6593720/207288861-122c2070-be07-4ed4-b504-3ddfd787b044.png)
Cant seem to see anything in the logs

**Comment by alexsee** [comment]
Sorry for the super late reply.

I came across this error when updating from an older version due to the related folders all being in wwwroot. But this shouldn't be an issue if you are setting it up fresh.

When do you see this issue? In the Umbraco Backend or for your page?

**Comment by kristianschneider** [comment]
Its when I try and access the umbraco backend ( /umbraco/ ) 

Frontend is ok. 
![image](https://user-images.githubusercontent.com/6593720/213991604-a7ead015-b246-4946-8ac2-356541ca3c01.png)

**Comment by alexsee** [comment]
I can reproduce your reported behavior. This is due to the unfortunate umbraco folder structure that `wwwroot` also contains the `umbraco` folder. This folder is part of the container image but is overwritten by the docker-compose configuration I proposed.

The current workaround is that you include each individual subfolder from `wwwroot` instead, for example:
```
    volumes:
      - ./Logs:/output/umbraco/Logs
      - ./uSync:/output/uSync
      - ./Views:/output/Views
      - ./wwwroot/css:/output/wwwroot/css
      - ./wwwroot/fonts:/output/wwwroot/fonts
      - ./wwwroot/media:/output/wwwroot/media
      - ./appsettings.json:/output/appsettings.json
      - ./Data:/output/umbraco/Data
```

**Comment by kristianschneider** [comment]
Great stuff. That works for me Alex

**Comment by Jogai** [comment]
This helped me too with my own setup of Umbraco 12 in docker. 

Vielen dank ;)
