### ISSUE TITLE
DeliveryApi Not Working

### ISSUE THREAD

**Issue by stuartwells** [alexsee/umbraco-container#65]
I am using your latest v13 Umbraco image and hosting it in Docker Desktop (Windows) as a multi container compose with SQL Server.

My experience with Umbraco is low (as is experience of docker), so I could be mis-understanding but having followed the information primary at this location: https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api I believe v13 supports DeliveryApi 'out of the box' but I need to add an additional entry in the appsettings.json.

I have done that in its basic form below (below is a reduced snippet - I 'obviously' kept the existing CMS structure and appended DeliveryApi), however I keep getting a 401 UnAuthorised if I try to call the API.

```json
{
    "Umbraco": {
        "CMS": {
            "DeliveryApi": {
                "Enabled": true
            }
        }
    }
}
```
```json
{
    "type": "https://tools.ietf.org/html/rfc9110#section-15.5.2",
    "title": "Unauthorized",
    "status": 401,
    "traceId": "00-f93755e86a72704f2456de7b06eedcd5-8ee7844f2ea640ef-00"
}
```

Having looked at the git repo, and specifically the appsettings-schema.json, the "CMS" entry in the appsettings.json does not seem to include the possibly of declaring a DeliveryApi entry.

I am therefore deducing that I will continue to get an 401 UnAuthorised because the entry I am adding to the appsettings is not being loaded/recognised?

Having added the above I should be able to call a basic get using Postman on the URL: http://localhost/umbraco/delivery/api/v2/content

The appsettings-schema.Umbraco.Cms.json does however contain the DeliveryApi definition, so perhaps that is correct and it shouldn't be in the appsettings-schema.json?

**Comment by alexsee** [comment]
The actual project template is from an older Umbraco version (likely v11), so I needed to add `.AddDeliveryApi()` to activate the respective service in dependency injection. The new image that I will create right now should work then.

**Comment by stuartwells** [comment]
I pulled the latest - well technically I had to pull explicit sha-2425b2b as it isn't yet being recognised as latest by docker - and I can confirm the DeliveryApi is now working nicely.

I turned off 'public' access and used an ApiKey, e.g.

```json
  "Umbraco": {
    "CMS": {
      "DeliveryApi": {
        "Enabled": true,
        "PublicAccess": false,
        "ApiKey": "my-api-key",
        "DisallowedContentTypeAliases": ["alias1", "alias2", "alias3"],
        "RichTextOutputAsJson": false
      }
    }
  },
```

REALLY appreciate the quick response to this as it was really blocking my investigation into how all this works - thanks a lot.
